// Danh mục đầy đủ 34 Tỉnh / Thành Phố và Phường / Xã / Thị Trấn theo Nghị quyết 202/2025/QH15 sắp xếp mới nhất

export const PROVINCE_OPTIONS = [
  // 6 Thành phố trực thuộc Trung ương
  'TP. Hồ Chí Minh',
  'TP. Hà Nội',
  'TP. Đà Nẵng',
  'TP. Hải Phòng',
  'TP. Cần Thơ',
  'TP. Huế',

  // 28 Tỉnh theo sắp xếp chính thức
  'An Giang',
  'Bắc Kạn',
  'Bắc Ninh',
  'Cà Mau',
  'Cao Bằng',
  'Đắk Lắk',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Tĩnh',
  'Hưng Yên',
  'Khánh Hòa',
  'Lai Châu',
  'Lạng Sơn',
  'Lào Cai',
  'Lâm Đồng',
  'Nghệ An',
  'Ninh Bình',
  'Phú Thọ',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sơn La',
  'Tây Ninh',
  'Thanh Hóa',
  'Tuyên Quang',
  'Vĩnh Long',

  // Các tỉnh / thị trường BĐS trọng điểm phụ trợ truyền thống
  'Long An',
  'Bình Dương',
  'Bà Rịa - Vũng Tàu',
  'Kiên Giang',
  'Bình Thuận',
  'Tỉnh thành khác',
];

export const PROVINCE_DISTRICTS: Record<string, string[]> = {
  'TP. Hồ Chí Minh': [
    // Quận 1
    'P. Bến Thành, Quận 1',
    'P. Bến Nghé, Quận 1',
    'P. Đa Kao, Quận 1',
    'P. Tân Định, Quận 1',
    'P. Nguyễn Thái Bình, Quận 1',
    'P. Phạm Ngũ Lão, Quận 1',
    'P. Cầu Kho, Quận 1',
    'P. Cầu Ông Lãnh, Quận 1',
    'P. Cô Giang, Quận 1',
    'P. Nguyễn Cư Trinh, Quận 1',

    // Quận 3 (Võ Thị Sáu)
    'P. Võ Thị Sáu, Quận 3',
    'P. 1, Quận 3',
    'P. 2, Quận 3',
    'P. 3, Quận 3',
    'P. 4, Quận 3',
    'P. 5, Quận 3',
    'P. 9, Quận 3',
    'P. 10, Quận 3',
    'P. 11, Quận 3',
    'P. 12, Quận 3',
    'P. 14, Quận 3',

    // TP. Thủ Đức
    'P. Thảo Điền, TP. Thủ Đức',
    'P. An Phú, TP. Thủ Đức',
    'P. Thủ Thiêm, TP. Thủ Đức',
    'P. An Khánh, TP. Thủ Đức',
    'P. Bình Trưng Tây, TP. Thủ Đức',
    'P. Bình Trưng Đông, TP. Thủ Đức',
    'P. Thạnh Mỹ Lợi, TP. Thủ Đức',
    'P. Hiệp Bình Chánh, TP. Thủ Đức',
    'P. Hiệp Bình Phước, TP. Thủ Đức',
    'P. Linh Trung, TP. Thủ Đức',
    'P. Linh Chiểu, TP. Thủ Đức',
    'P. Linh Đông, TP. Thủ Đức',
    'P. Linh Tây, TP. Thủ Đức',
    'P. Phước Long A, TP. Thủ Đức',
    'P. Phước Long B, TP. Thủ Đức',
    'P. Tăng Nhơn Phú A, TP. Thủ Đức',
    'P. Tăng Nhơn Phú B, TP. Thủ Đức',
    'P. Long Thạnh Mỹ, TP. Thủ Đức (Vinhomes Grand Park)',
    'P. Long Bình, TP. Thủ Đức',

    // Quận 7
    'P. Tân Phong, Quận 7 (Phú Mỹ Hưng)',
    'P. Tân Phú, Quận 7',
    'P. Phú Mỹ, Quận 7',
    'P. Phú Thuận, Quận 7',
    'P. Tân Quy, Quận 7',
    'P. Tân Kiểng, Quận 7',
    'P. Tân Hưng, Quận 7',
    'P. Bình Thuận, Quận 7',

    // Bình Thạnh & Phú Nhuận
    'P. 19, Bình Thạnh (Thị Nghè)',
    'P. 22, Bình Thạnh (Vinhomes Central Park)',
    'P. 25, Bình Thạnh (Hàng Xanh)',
    'P. 27, Bình Thạnh (Thanh Đa)',
    'P. 28, Bình Thạnh (Bình Quới)',
    'P. 7, Phú Nhuận (Phan Xích Long)',
    'P. 1, Phú Nhuận',
    'P. 2, Phú Nhuận',
    'P. 9, Phú Nhuận',

    // Quận 10 & Quận 11
    'P. 12, Quận 10 (Kỳ Hòa)',
    'P. 14, Quận 10 (Bắc Hải)',
    'P. 15, Quận 11 (Đầm Sen)',
    'P. 1, Quận 11',
    'P. 3, Quận 11',
    'P. 5, Quận 11',
    'P. Bình Thới, Quận 11',

    // Hóc Môn & Cần Giờ (Các dự án trọng điểm)
    'Xã Tân Thới Nhì, Huyện Hóc Môn (Khu đô thị sinh thái)',
    'Xã Xuân Thới Thượng, Huyện Hóc Môn',
    'Xã Bà Điểm, Huyện Hóc Môn',
    'TT. Cần Thạnh, Huyện Cần Giờ (Đại đô thị lấn biển Vinhomes)',
    'Xã Long Hòa, Huyện Cần Giờ',
    'Xã Bình Khánh, Huyện Cần Giờ',

    // Huyện Bình Chánh & Nhà Bè
    'Xã Bình Hưng, Huyện Bình Chánh (Khu Trung Sơn)',
    'Xã Phong Phú, Huyện Bình Chánh',
    'Xã Phước Kiển, Huyện Nhà Bè',
    'Xã Phú Xuân, Huyện Nhà Bè',
  ],

  'TP. Hà Nội': [
    'P. Tràng Tiền, Quận Hoàn Kiếm',
    'P. Hàng Bạc, Quận Hoàn Kiếm',
    'P. Lý Thái Tổ, Quận Hoàn Kiếm',
    'P. Hàng Gai, Quận Hoàn Kiếm',
    'P. Điện Biên, Quận Ba Đình',
    'P. Đội Cấn, Quận Ba Đình',
    'P. Giảng Võ, Quận Ba Đình',
    'P. Kim Mã, Quận Ba Đình',
    'P. Dịch Vọng, Quận Cầu Giấy',
    'P. Dịch Vọng Hậu, Quận Cầu Giấy',
    'P. Trung Hòa, Quận Cầu Giấy',
    'P. Yên Hòa, Quận Cầu Giấy',
    'P. Quảng An, Quận Tây Hồ',
    'P. Nhật Tân, Quận Tây Hồ',
    'P. Xuân La, Quận Tây Hồ',
    'P. Ô Chợ Dừa, Quận Đống Đa',
    'P. Láng Hạ, Quận Đống Đa',
    'P. Mỹ Đình 1, Quận Nam Từ Liêm',
    'P. Mỹ Đình 2, Quận Nam Từ Liêm',
    'P. Mễ Trì, Quận Nam Từ Liêm',
    'P. Phú Diễn, Quận Bắc Từ Liêm',
    'P. Cổ Nhuế 1, Quận Bắc Từ Liêm',
  ],

  'TP. Đà Nẵng': [
    'P. Hải Châu I, Quận Hải Châu',
    'P. Hải Châu II, Quận Hải Châu',
    'P. Thạch Thang, Quận Hải Châu',
    'P. Hòa Cường Bắc, Quận Hải Châu',
    'P. Hòa Cường Nam, Quận Hải Châu',
    'P. An Hải Bắc, Quận Sơn Trà',
    'P. An Hải Tây, Quận Sơn Trà',
    'P. Phước Mỹ, Quận Sơn Trà (Biển Mỹ Khê)',
    'P. Mỹ An, Quận Ngũ Hành Sơn',
    'P. Khuê Mỹ, Quận Ngũ Hành Sơn',
    'P. Hòa Khánh Bắc, Quận Liên Chiểu',
    'P. Khuê Trung, Quận Cẩm Lệ',
  ],

  'TP. Hải Phòng': [
    'P. Minh Khai, Quận Hồng Bàng',
    'P. Hoàng Văn Thụ, Quận Hồng Bàng',
    'P. Cầu Đất, Quận Ngô Quyền',
    'P. Lạc Viên, Quận Ngô Quyền',
    'P. An Biên, Quận Lê Chân',
    'P. Đằng Hải, Quận Hải An',
    'P. Đằng Lâm, Quận Hải An',
    'P. Vạn Hương, Quận Đồ Sơn (Khu du lịch Đồ Sơn)',
    'TT. Núi Đèo, Huyện Thủy Nguyên',
    'TT. Cát Bà, Huyện Cát Hải',
  ],

  'TP. Cần Thơ': [
    'P. Tân An, Quận Ninh Kiều (Bến Ninh Kiều)',
    'P. An Cư, Quận Ninh Kiều',
    'P. An Hòa, Quận Ninh Kiều',
    'P. Cái Khế, Quận Ninh Kiều',
    'P. Xuân Khánh, Quận Ninh Kiều',
    'P. Hưng Phú, Quận Cái Răng',
    'P. Lê Bình, Quận Cái Răng',
    'P. Trà An, Quận Bình Thủy',
    'P. Châu Văn Liêm, Quận Ô Môn',
    'P. Thốt Nốt, Quận Thốt Nốt',
  ],

  'TP. Huế': [
    'P. Phú Hội, TP. Huế (Phố Tây Huế)',
    'P. Vĩnh Ninh, TP. Huế',
    'P. Thuận Hòa, TP. Huế',
    'P. Tây Lộc, TP. Huế',
    'P. Kim Long, TP. Huế',
    'P. Vỹ Dạ, TP. Huế',
    'P. Thủy Xuân, TP. Huế',
    'P. An Đông, TP. Huế',
    'P. Phú Bài, TX. Hương Thủy',
    'TT. Lăng Cô, Huyện Phú Lộc',
  ],

  'Đồng Nai': [
    'P. Trảng Dài, TP. Biên Hòa',
    'P. Tân Phong, TP. Biên Hòa',
    'P. Hố Nai, TP. Biên Hòa',
    'P. Tân Hòa, TP. Biên Hòa',
    'P. Tam Hiệp, TP. Biên Hòa',
    'P. Thống Nhất, TP. Biên Hòa',
    'P. Quyết Thắng, TP. Biên Hòa',
    'P. Bửu Long, TP. Biên Hòa',
    'P. Bửu Hòa, TP. Biên Hòa',
    'P. Hiệp Hòa (Cù Lao Phố), TP. Biên Hòa',
    'P. Long Bình Tân, TP. Biên Hòa',
    'P. Long Bình, TP. Biên Hòa',
    'P. An Bình, TP. Biên Hòa',
    'Xã Long Hưng, TP. Biên Hòa (Aqua City)',
    'TT. Vĩnh An, Huyện Vĩnh Cửu',
    'Xã Mã Đà, Huyện Vĩnh Cửu (Hồ Trị An)',
    'Xã Trị An, Huyện Vĩnh Cửu',
    'TT. Long Thành, Huyện Long Thành',
    'Xã Bình Sơn, Huyện Long Thành (Sân Bay Long Thành)',
    'Xã Lộc An, Huyện Long Thành',
    'TT. Hiệp Phước, Huyện Nhơn Trạch',
    'Xã Đại Phước, Huyện Nhơn Trạch (SwanBay)',
    'Xã Phú Hội, Huyện Nhơn Trạch',
    'P. Xuân An, TP. Long Khánh',
    'TT. Trảng Bom, Huyện Trảng Bom',
  ],

  'Long An': [
    'P. 1, TP. Tân An',
    'P. 2, TP. Tân An',
    'P. 3, TP. Tân An',
    'P. 4, TP. Tân An',
    'P. 5, TP. Tân An',
    'P. 6, TP. Tân An',
    'P. 7, TP. Tân An',
    'TT. Bến Lức, Huyện Bến Lức',
    'Xã An Thạnh, Huyện Bến Lức (Waterpoint Nam Long)',
    'Xã Thạnh Đức, Huyện Bến Lức',
    'Xã Lương Hòa, Huyện Bến Lức',
    'TT. Cần Giuộc, Huyện Cần Giuộc',
    'Xã Long Hậu, Huyện Cần Giuộc',
    'Xã Phước Lý, Huyện Cần Giuộc',
    'TT. Hậu Nghĩa, Huyện Đức Hòa',
    'TT. Đức Hòa, Huyện Đức Hòa',
    'Xã Mỹ Hạnh Nam, Huyện Đức Hòa',
    'Xã Đức Hòa Hạ, Huyện Đức Hòa',
    'TT. Cần Đước, Huyện Cần Đước',
    'Xã Long Cang, Huyện Cần Đước',
    'TT. Thủ Thừa, Huyện Thủ Thừa',
  ],

  'Bình Dương': [
    'P. Phú Cường, TP. Thủ Dầu Một',
    'P. Hiệp Thành, TP. Thủ Dầu Một',
    'P. Chánh Nghĩa, TP. Thủ Dầu Một',
    'P. Phú Hòa, TP. Thủ Dầu Một',
    'P. Hòa Phú (Thành Phố Mới), TP. Thủ Dầu Một',
    'P. Dĩ An, TP. Dĩ An',
    'P. Đông Hòa, TP. Dĩ An',
    'P. Tân Đông Hiệp, TP. Dĩ An',
    'P. Lái Thiêu, TP. Thuận An',
    'P. An Phú, TP. Thuận An',
    'P. Mỹ Phước, TP. Bến Cát',
    'P. Uyên Hưng, TP. Tân Uyên',
    'TT. Lai Uyên, Huyện Bàu Bàng',
  ],

  'Bà Rịa - Vũng Tàu': [
    'P. 1, TP. Vũng Tàu (Bãi Trước)',
    'P. 2, TP. Vũng Tàu (Bãi Sau)',
    'P. 7, TP. Vũng Tàu',
    'P. 8, TP. Vũng Tàu',
    'P. Thắng Tam, TP. Vũng Tàu (Bãi Thùy Vân)',
    'P. Nguyễn An Ninh, TP. Vũng Tàu',
    'Xã Bình Châu, Huyện Xuyên Mộc (Suối Khoáng Nóng)',
    'Xã Phước Thuận, Huyện Xuyên Mộc (Hồ Tràm Strip)',
    'P. Phú Mỹ, TX. Phú Mỹ',
    'P. Tân Phước, TX. Phú Mỹ (Cảng Cái Mép)',
    'P. Phước Trung, TP. Bà Rịa',
    'TT. Long Hải, Huyện Long Điền',
  ],

  'Khánh Hòa': [
    'P. Lộc Thọ, TP. Nha Trang (Đường Trần Phú)',
    'P. Phước Tiến, TP. Nha Trang',
    'P. Tân Lập, TP. Nha Trang',
    'P. Vĩnh Hải, TP. Nha Trang',
    'P. Vĩnh Hòa, TP. Nha Trang',
    'P. Phước Long, TP. Nha Trang',
    'Xã Cam Hải Đông, Huyện Cam Lâm (Bãi Dài)',
    'P. Cam Nghĩa, TP. Cam Ranh',
    'Xã Vạn Thạnh, Huyện Vạn Ninh (Bắc Vân Phong)',
  ],

  'Lâm Đồng': [
    'P. 1, TP. Đà Lạt (Chợ Đà Lạt & Hồ Xuân Hương)',
    'P. 2, TP. Đà Lạt',
    'P. 3, TP. Đà Lạt',
    'P. 4, TP. Đà Lạt',
    'P. 8, TP. Đà Lạt (Thung Lũng Tình Yêu)',
    'P. 9, TP. Đà Lạt',
    'P. 10, TP. Đà Lạt',
    'P. 1, TP. Bảo Lộc',
    'P. B\'Lao, TP. Bảo Lộc',
    'TT. Liên Nghĩa, Huyện Đức Trọng',
  ],

  'Kiên Giang': [
    'P. Dương Đông, TP. Phú Quốc',
    'P. An Thới, TP. Phú Quốc (Nam Đảo)',
    'Xã Hàm Ninh, TP. Phú Quốc',
    'Xã Gành Dầu, TP. Phú Quốc (Grand World)',
    'Xã Dương Tơ, TP. Phú Quốc (Bãi Trường)',
    'P. Vĩnh Thanh Vân, TP. Rạch Giá',
    'P. Pháo Đài, TP. Hà Tiên',
  ],

  'Bình Thuận': [
    'P. Hàm Tiến, TP. Phan Thiết (Mũi Né)',
    'P. Mũi Né, TP. Phan Thiết',
    'P. Phú Thủy, TP. Phan Thiết',
    'Xã Tiến Thành, TP. Phan Thiết (NovaWorld Phan Thiết)',
    'P. Phước Hội, TX. La Gi',
    'Xã Tân Thành, Huyện Hàm Thuận Nam (Mũi Kê Gà)',
  ],

  'Bắc Ninh': [
    'P. Suối Hoa, TP. Bắc Ninh',
    'P. Tiền An, TP. Bắc Ninh',
    'P. Đại Phúc, TP. Bắc Ninh',
    'P. Đồng Kỵ, TP. Từ Sơn',
    'P. Trang Hạ, TP. Từ Sơn',
    'TT. Chờ, Huyện Yên Phong',
    'P. Hồ, TX. Thuận Thành',
  ],

  'Hưng Yên': [
    'P. Hiến Nam, TP. Hưng Yên',
    'P. An Tảo, TP. Hưng Yên',
    'Xã Xuân Quan, Huyện Văn Giang (Ecopark)',
    'Xã Phụng Công, Huyện Văn Giang',
    'P. Bần Yên Nhân, TX. Mỹ Hào',
    'TT. Yên Mỹ, Huyện Yên Mỹ',
  ],

  'Quảng Ninh': [
    'P. Bãi Cháy, TP. Hạ Long (Khu du lịch Sun World)',
    'P. Hòn Gai, TP. Hạ Long',
    'P. Tuần Châu, TP. Hạ Long',
    'P. Hồng Gai, TP. Hạ Long',
    'P. Cẩm Trung, TP. Cẩm Phả',
    'P. Trần Phú, TP. Móng Cái',
    'TT. Cái Rồng, Huyện Vân Đồn',
  ],

  'Thanh Hóa': [
    'P. Điện Biên, TP. Thanh Hóa',
    'P. Lam Sơn, TP. Thanh Hóa',
    'P. Đông Thọ, TP. Thanh Hóa',
    'P. Trường Sơn, TP. Sầm Sơn',
    'P. Bắc Sơn, TP. Sầm Sơn (FLC Sầm Sơn)',
    'P. Hải Hòa, TX. Nghi Sơn',
  ],

  'Nghệ An': [
    'P. Trường Thi, TP. Vinh',
    'P. Lê Lợi, TP. Vinh',
    'P. Hưng Dũng, TP. Vinh',
    'P. Thu Thủy, TX. Cửa Lò',
    'P. Nghi Hương, TX. Cửa Lò',
    'TT. Diễn Châu, Huyện Diễn Châu',
  ],

  'Hà Tĩnh': [
    'P. Trần Phú, TP. Hà Tĩnh',
    'P. Bắc Hà, TP. Hà Tĩnh',
    'P. Nam Hà, TP. Hà Tĩnh',
    'P. Bắc Hồng, TX. Hồng Lĩnh',
    'P. Sông Trí, TX. Kỳ Anh',
    'TT. Xuân An, Huyện Nghi Xuân',
  ],

  'Quảng Trị': [
    'P. 1, TP. Đông Hà',
    'P. 2, TP. Đông Hà',
    'P. 5, TP. Đông Hà',
    'P. 1, TX. Quảng Trị',
    'P. 2, TX. Quảng Trị',
    'TT. Cửa Tùng, Huyện Vĩnh Linh',
  ],

  'Quảng Ngãi': [
    'P. Trần Phú, TP. Quảng Ngãi',
    'P. Lê Hồng Phong, TP. Quảng Ngãi',
    'P. Nghĩa Chánh, TP. Quảng Ngãi',
    'TT. Châu Ổ, Huyện Bình Sơn (KKT Dung Quất)',
    'Huyện Đảo Lý Sơn',
  ],

  'Ninh Bình': [
    'P. Vân Giang, TP. Ninh Bình',
    'P. Ninh Khánh, TP. Ninh Bình',
    'P. Nam Thành, TP. Ninh Bình',
    'P. Bắc Sơn, TP. Tam Điệp',
    'Xã Ninh Hải, Huyện Hoa Lư (Tam Cốc - Bích Động)',
    'TT. Phát Diệm, Huyện Kim Sơn',
  ],

  'Phú Thọ': [
    'P. Gia Cẩm, TP. Việt Trì',
    'P. Tiên Cát, TP. Việt Trì',
    'P. Nông Trang, TP. Việt Trì',
    'Xã Hy Cương, TP. Việt Trì (Đền Hùng)',
    'TT. Thanh Thủy, Huyện Thanh Thủy (Khoáng nóng)',
  ],

  'Tây Ninh': [
    'P. 1, TP. Tây Ninh',
    'P. 2, TP. Tây Ninh',
    'P. 3, TP. Tây Ninh',
    'P. Trảng Bàng, TX. Trảng Bàng',
    'P. Long Hoa, TX. Hòa Thành (Tòa Thánh Tây Ninh)',
    'TT. Gò Dầu, Huyện Gò Dầu',
  ],

  'An Giang': [
    'P. Mỹ Long, TP. Long Xuyên',
    'P. Mỹ Bình, TP. Long Xuyên',
    'P. Châu Phú A, TP. Châu Đốc (Miếu Bà Chúa Xứ)',
    'P. Châu Phú B, TP. Châu Đốc',
    'P. Long Thạnh, TX. Tân Châu',
  ],

  'Đồng Tháp': [
    'P. 1, TP. Cao Lãnh',
    'P. 2, TP. Cao Lãnh',
    'P. 1, TP. Sa Đéc (Làng Hoa Sa Đéc)',
    'P. An Thạnh, TP. Hồng Ngự',
    'TT. Lai Vung, Huyện Lai Vung',
  ],

  'Vĩnh Long': [
    'P. 1, TP. Vĩnh Long',
    'P. 2, TP. Vĩnh Long',
    'P. 4, TP. Vĩnh Long',
    'P. Cái Vồn, TX. Bình Minh',
    'TT. Long Hồ, Huyện Long Hồ',
  ],

  'Cà Mau': [
    'P. 1, TP. Cà Mau',
    'P. 2, TP. Cà Mau',
    'P. 5, TP. Cà Mau',
    'P. 9, TP. Cà Mau',
    'TT. Năm Căn, Huyện Năm Căn',
    'Xã Đất Mũi, Huyện Ngọc Hiển',
  ],

  'Đắk Lắk': [
    'P. Thắng Lợi, TP. Buôn Ma Thuột',
    'P. Tân Lập, TP. Buôn Ma Thuột',
    'P. Tân An, TP. Buôn Ma Thuột (EcoCity Premia)',
    'P. Tự An, TP. Buôn Ma Thuột',
    'P. Đoàn Kết, TX. Buôn Hồ',
  ],

  'Gia Lai': [
    'P. Diên Hồng, TP. Pleiku',
    'P. Hội Thương, TP. Pleiku',
    'P. Hoa Lư, TP. Pleiku',
    'P. Tây Sơn, TP. Pleiku',
    'P. An Bình, TX. An Khê',
  ],

  'Lào Cai': [
    'P. Cốc Lếu, TP. Lào Cai',
    'P. Kim Tân, TP. Lào Cai',
    'P. Sa Pa, TX. Sa Pa',
    'P. Hàm Rồng, TX. Sa Pa',
    'P. Phan Si Păng, TX. Sa Pa',
  ],

  'Lạng Sơn': [
    'P. Vĩnh Trại, TP. Lạng Sơn',
    'P. Tam Thanh, TP. Lạng Sơn',
    'P. Hoàng Văn Thụ, TP. Lạng Sơn',
    'TT. Đồng Đăng, Huyện Cao Lộc',
    'TT. Hữu Lũng, Huyện Hữu Lũng',
  ],

  'Sơn La': [
    'P. Chiềng Lề, TP. Sơn La',
    'P. Tô Hiệu, TP. Sơn La',
    'P. Quyết Thắng, TP. Sơn La',
    'TT. Mộc Châu, Huyện Mộc Châu',
    'TT. Nông Trường Mộc Châu, Huyện Mộc Châu',
  ],

  'Điện Biên': [
    'P. Mường Thanh, TP. Điện Biên Phủ',
    'P. Nam Thanh, TP. Điện Biên Phủ',
    'P. Thanh Bình, TP. Điện Biên Phủ',
    'TT. Mường Nhé, Huyện Mường Nhé',
  ],

  'Lai Châu': [
    'P. Đoàn Kết, TP. Lai Châu',
    'P. Tân Phong, TP. Lai Châu',
    'P. Đông Phong, TP. Lai Châu',
    'TT. Tam Đường, Huyện Tam Đường',
  ],

  'Cao Bằng': [
    'P. Hợp Giang, TP. Cao Bằng',
    'P. Sông Hiến, TP. Cao Bằng',
    'P. Đề Thám, TP. Cao Bằng',
    'TT. Trùng Khánh, Huyện Trùng Khánh (Thác Bản Giốc)',
  ],

  'Tuyên Quang': [
    'P. Phan Thiết, TP. Tuyên Quang',
    'P. Tân Quang, TP. Tuyên Quang',
    'P. Minh Xuân, TP. Tuyên Quang',
    'TT. Sơn Dương, Huyện Sơn Dương',
  ],

  'Bắc Kạn': [
    'P. Đức Xuân, TP. Bắc Kạn',
    'P. Sông Cầu, TP. Bắc Kạn',
    'P. Phùng Chí Kiên, TP. Bắc Kạn',
    'TT. Chợ Rã, Huyện Ba Bể (Hồ Ba Bể)',
  ],
};
