// Danh mục Tỉnh / Thành Phố và Phường / Xã / Thị Trấn theo thông tin sáp nhập đơn vị hành chính mới nhất

export const PROVINCE_OPTIONS = [
  'TP. Hồ Chí Minh',
  'Long An',
  'Đồng Nai',
  'Bình Dương',
  'Bà Rịa - Vũng Tàu',
  'Hà Nội',
  'Đà Nẵng',
  'Khánh Hòa',
  'Lâm Đồng',
  'Kiên Giang',
  'Cần Thơ',
  'Bình Thuận',
  'Tỉnh thành khác',
];

export const PROVINCE_DISTRICTS: Record<string, string[]> = {
  'TP. Hồ Chí Minh': [
    // Quận 1 (Phường theo sắp xếp mới nhất)
    'P. Bến Thành, Quận 1',
    'P. Bến Nghé, Quận 1',
    'P. Đa Kao, Quận 1',
    'P. Tân Định, Quận 1',
    'P. Nguyễn Thái Bình, Quận 1',
    'P. Phạm Ngũ Lão, Quận 1',
    'P. Cầu Kho, Quận 1',
    'P. Cầu Ông Lãnh, Quận 1',
    'P. Cô Giang, Quận 1',
    'P. Nguyễn Cư Trinh, Quận 1',

    // Quận 3 (Gộp P.6, P.7, P.8 thành P. Võ Thị Sáu)
    'P. Võ Thị Sáu, Quận 3',
    'P. 1, Quận 3',
    'P. 2, Quận 3',
    'P. 3, Quận 3',
    'P. 4, Quận 3',
    'P. 5, Quận 3',
    'P. 9, Quận 3',
    'P. 10, Quận 3',
    'P. 11, Quận 3',
    'P. 12, Quận 3',
    'P. 14, Quận 3',

    // TP. Thủ Đức (Các phường trọng điểm)
    'P. Thảo Điền, TP. Thủ Đức',
    'P. An Phú, TP. Thủ Đức',
    'P. Thủ Thiêm, TP. Thủ Đức',
    'P. An Khánh, TP. Thủ Đức',
    'P. Bình Trưng Tây, TP. Thủ Đức',
    'P. Bình Trưng Đông, TP. Thủ Đức',
    'P. Thạnh Mỹ Lợi, TP. Thủ Đức',
    'P. Hiệp Bình Chánh, TP. Thủ Đức',
    'P. Hiệp Bình Phước, TP. Thủ Đức',
    'P. Linh Trung, TP. Thủ Đức',
    'P. Linh Chiểu, TP. Thủ Đức',
    'P. Linh Đông, TP. Thủ Đức',
    'P. Linh Tây, TP. Thủ Đức',
    'P. Phước Long A, TP. Thủ Đức',
    'P. Phước Long B, TP. Thủ Đức',
    'P. Tăng Nhơn Phú A, TP. Thủ Đức',
    'P. Tăng Nhơn Phú B, TP. Thủ Đức',
    'P. Long Thạnh Mỹ, TP. Thủ Đức',
    'P. Long Bình, TP. Thủ Đức',

    // Quận 7
    'P. Tân Phong, Quận 7 (Phú Mỹ Hưng)',
    'P. Tân Phú, Quận 7',
    'P. Phú Mỹ, Quận 7',
    'P. Phú Thuận, Quận 7',
    'P. Tân Quy, Quận 7',
    'P. Tân Kiểng, Quận 7',
    'P. Tân Hưng, Quận 7',
    'P. Tân Thuận Đông, Quận 7',
    'P. Tân Thuận Tây, Quận 7',
    'P. Bình Thuận, Quận 7',

    // Bình Thạnh
    'P. 19, Bình Thạnh (Thị Nghè)',
    'P. 21, Bình Thạnh',
    'P. 22, Bình Thạnh (Vinhomes Central Park)',
    'P. 25, Bình Thạnh (Hàng Xanh)',
    'P. 26, Bình Thạnh',
    'P. 27, Bình Thạnh (Thanh Đa)',
    'P. 28, Bình Thạnh (Bình Quới)',
    'P. 2, Bình Thạnh',
    'P. 3, Bình Thạnh',
    'P. 11, Bình Thạnh',
    'P. 14, Bình Thạnh',

    // Phú Nhuận
    'P. 1, Phú Nhuận',
    'P. 2, Phú Nhuận',
    'P. 7, Phú Nhuận (Phan Xích Long)',
    'P. 8, Phú Nhuận',
    'P. 9, Phú Nhuận',
    'P. 10, Phú Nhuận',
    'P. 15, Phú Nhuận',
    'P. 17, Phú Nhuận',

    // Tân Bình
    'P. 2, Tân Bình (Khu Sân Bay)',
    'P. 4, Tân Bình',
    'P. 12, Tân Bình',
    'P. 13, Tân Bình',
    'P. 14, Tân Bình',
    'P. 15, Tân Bình',

    // Quận 10
    'P. 1, Quận 10',
    'P. 2, Quận 10',
    'P. 4, Quận 10',
    'P. 10, Quận 10',
    'P. 12, Quận 10 (Hà Đô Centrosa)',
    'P. 14, Quận 10',
    'P. 15, Quận 10',

    // Quận 4 (sáp nhập các phường)
    'P. 1, Quận 4',
    'P. 2, Quận 4',
    'P. 3, Quận 4',
    'P. 4, Quận 4',
    'P. 6, Quận 4',
    'P. 8, Quận 4',
    'P. 9, Quận 4',
    'P. 13, Quận 4',
    'P. 14, Quận 4',
    'P. 18, Quận 4',

    // Quận 5
    'P. 1, Quận 5',
    'P. 2, Quận 5',
    'P. 5, Quận 5 (Chợ Lớn)',
    'P. 6, Quận 5',
    'P. 7, Quận 5',
    'P. 11, Quận 5',

    // Nhà Bè & Bình Chánh
    'Xã Phước Kiển, Nhà Bè',
    'Xã Nhơn Đức, Nhà Bè',
    'Xã Phú Xuân, Nhà Bè',
    'Xã Hiệp Phước, Nhà Bè',
    'TT. Nhà Bè',
    'Xã Bình Hưng, Bình Chánh (KDC Trung Sơn)',
    'Xã Phong Phú, Bình Chánh',
    'Xã Vĩnh Lộc A, Bình Chánh',
    'Xã Vĩnh Lộc B, Bình Chánh',
    'TT. Tân Túc, Bình Chánh',
  ],

  'Long An': [
    // TP. Tân An (Đầy đủ phường/xã)
    'P. 1, TP. Tân An',
    'P. 2, TP. Tân An',
    'P. 3, TP. Tân An',
    'P. 4, TP. Tân An',
    'P. 5, TP. Tân An',
    'P. 6, TP. Tân An',
    'P. 7, TP. Tân An',
    'P. Khánh Hậu, TP. Tân An',
    'P. Tân Khánh, TP. Tân An',
    'Xã Bình Tâm, TP. Tân An',
    'Xã Lợi Bình Nhơn, TP. Tân An',
    'Xã Hướng Thọ Phú, TP. Tân An',
    'Xã An Vĩnh Ngãi, TP. Tân An',

    // Huyện Bến Lức
    'TT. Bến Lức, Huyện Bến Lức',
    'Xã An Thạnh, Huyện Bến Lức (KĐT Waterpoint)',
    'Xã Thạnh Đức, Huyện Bến Lức',
    'Xã Lương Hòa, Huyện Bến Lức',
    'Xã Lương Bình, Huyện Bến Lức',
    'Xã Mỹ Yên, Huyện Bến Lức',
    'Xã Nhựt Chánh, Huyện Bến Lức',
    'Xã Tân Bửu, Huyện Bến Lức',
    'Xã Tân Hòa, Huyện Bến Lức',
    'Xã Thạnh Hòa, Huyện Bến Lức',
    'Xã Thạnh Lợi, Huyện Bến Lức',
    'Xã Thạnh Phú, Huyện Bến Lức',
    'Xã Bình Đức, Huyện Bến Lức',

    // Huyện Cần Giuộc
    'TT. Cần Giuộc, Huyện Cần Giuộc',
    'Xã Long Hậu, Huyện Cần Giuộc (KCN & KĐT Long Hậu)',
    'Xã Phước Lại, Huyện Cần Giuộc',
    'Xã Phước Vĩnh Tây, Huyện Cần Giuộc',
    'Xã Phước Vĩnh Đông, Huyện Cần Giuộc',
    'Xã Mỹ Lộc, Huyện Cần Giuộc',
    'Xã Long Phụng, Huyện Cần Giuộc',
    'Xã Đông Thạnh, Huyện Cần Giuộc',
    'Xã Tân Kim, Huyện Cần Giuộc',
    'Xã Tân Tập, Huyện Cần Giuộc (Cảng Quốc Tế Long An)',
    'Xã Long An, Huyện Cần Giuộc',
    'Xã Thuận Thành, Huyện Cần Giuộc',

    // Huyện Đức Hòa
    'TT. Đức Hòa, Huyện Đức Hòa',
    'TT. Hậu Nghĩa, Huyện Đức Hòa',
    'TT. Hiệp Hòa, Huyện Đức Hòa',
    'Xã Đức Hòa Hạ, Huyện Đức Hòa',
    'Xã Đức Hòa Đông, Huyện Đức Hòa',
    'Xã Đức Hòa Thượng, Huyện Đức Hòa',
    'Xã Mỹ Hạnh Nam, Huyện Đức Hòa',
    'Xã Mỹ Hạnh Bắc, Huyện Đức Hòa',
    'Xã Hựu Thạnh, Huyện Đức Hòa',
    'Xã An Ninh Tây, Huyện Đức Hòa',
    'Xã An Ninh Đông, Huyện Đức Hòa',
    'Xã Lộc Giang, Huyện Đức Hòa',

    // Huyện Cần Đước
    'TT. Cần Đước, Huyện Cần Đước',
    'Xã Long Cang, Huyện Cần Đước',
    'Xã Long Định, Huyện Cần Đước',
    'Xã Long Trạch, Huyện Cần Đước',
    'Xã Long Khê, Huyện Cần Đước',
    'Xã Phước Đông, Huyện Cần Đước',
    'Xã Tân Lân, Huyện Cần Đước',
    'Xã Tân Trạch, Huyện Cần Đước',
    'Xã Long Hựu Đông, Huyện Cần Đước',
    'Xã Long Hựu Tây, Huyện Cần Đước',

    // TX. Kiến Tường & Huyện khác
    'P. 1, TX. Kiến Tường',
    'P. 2, TX. Kiến Tường',
    'TT. Thủ Thừa, Huyện Thủ Thừa',
    'TT. Tầm Vu, Huyện Châu Thành',
  ],

  'Đồng Nai': [
    // TP. Biên Hòa
    'P. Trảng Dài, TP. Biên Hòa',
    'P. Tân Phong, TP. Biên Hòa',
    'P. Hố Nai, TP. Biên Hòa',
    'P. Tân Hòa, TP. Biên Hòa',
    'P. Tam Hiệp, TP. Biên Hòa',
    'P. Thống Nhất, TP. Biên Hòa',
    'P. Quyết Thắng, TP. Biên Hòa',
    'P. Bửu Long, TP. Biên Hòa',
    'P. Bửu Hòa, TP. Biên Hòa',
    'P. Hiệp Hòa (Cù Lao Phố), TP. Biên Hòa',
    'P. Long Bình Tân, TP. Biên Hòa',
    'P. Long Bình, TP. Biên Hòa',
    'P. An Bình, TP. Biên Hòa',
    'P. Tân Hiệp, TP. Biên Hòa',
    'P. Tân Tiến, TP. Biên Hòa',
    'P. Tân Hạnh, TP. Biên Hòa',
    'P. Hóa An, TP. Biên Hòa',
    'Xã Long Hưng, TP. Biên Hòa (Aqua City)',

    // Huyện Vĩnh Cửu
    'TT. Vĩnh An, Huyện Vĩnh Cửu',
    'Xã Mã Đà, Huyện Vĩnh Cửu (Hồ Trị An)',
    'Xã Phú Lý, Huyện Vĩnh Cửu',
    'Xã Trị An, Huyện Vĩnh Cửu',
    'Xã Vĩnh Tân, Huyện Vĩnh Cửu',
    'Xã Tân Bình, Huyện Vĩnh Cửu',
    'Xã Bình Lợi, Huyện Vĩnh Cửu',
    'Xã Thiện Tân, Huyện Vĩnh Cửu',
    'Xã Thạnh Phú, Huyện Vĩnh Cửu',

    // Huyện Long Thành
    'TT. Long Thành, Huyện Long Thành',
    'Xã Bình Sơn, Huyện Long Thành (Sân Bay Long Thành)',
    'Xã Lộc An, Huyện Long Thành',
    'Xã Long Đức, Huyện Long Thành',
    'Xã An Phước, Huyện Long Thành',
    'Xã Phước Thái, Huyện Long Thành',
    'Xã Tam An, Huyện Long Thành',
    'Xã Phước Bình, Huyện Long Thành',

    // Huyện Nhơn Trạch
    'TT. Hiệp Phước, Huyện Nhơn Trạch',
    'Xã Đại Phước, Huyện Nhơn Trạch (SwanBay)',
    'Xã Phú Hội, Huyện Nhơn Trạch',
    'Xã Phú Đông, Huyện Nhơn Trạch',
    'Xã Phú Thạnh, Huyện Nhơn Trạch',
    'Xã Long Tân, Huyện Nhơn Trạch',
    'Xã Phước Khánh, Huyện Nhơn Trạch',
    'Xã Phước An, Huyện Nhơn Trạch',

    // TP. Long Khánh & Trảng Bom
    'P. Xuân An, TP. Long Khánh',
    'P. Xuân Bình, TP. Long Khánh',
    'P. Suối Tre, TP. Long Khánh',
    'TT. Trảng Bom, Huyện Trảng Bom',
    'Xã Hố Nai 3, Huyện Trảng Bom',
    'Xã Giang Điền, Huyện Trảng Bom',
  ],

  'Bình Dương': [
    // TP. Thủ Dầu Một
    'P. Phú Cường, TP. Thủ Dầu Một',
    'P. Hiệp Thành, TP. Thủ Dầu Một',
    'P. Chánh Nghĩa, TP. Thủ Dầu Một',
    'P. Phú Hòa, TP. Thủ Dầu Một',
    'P. Phú Lợi, TP. Thủ Dầu Một',
    'P. Định Hòa, TP. Thủ Dầu Một',
    'P. Tân An, TP. Thủ Dầu Một',
    'P. Hòa Phú (Thành Phố Mới), TP. Thủ Dầu Một',

    // TP. Thuận An
    'P. Lái Thiêu, TP. Thuận An',
    'P. An Phú, TP. Thuận An',
    'P. Thuận Giao, TP. Thuận An',
    'P. Bình Hòa, TP. Thuận An',
    'P. Bình Chuẩn, TP. Thuận An',
    'P. Vĩnh Phú, TP. Thuận An',
    'P. An Thạnh, TP. Thuận An',

    // TP. Dĩ An
    'P. Dĩ An, TP. Dĩ An',
    'P. Tân Đông Hiệp, TP. Dĩ An',
    'P. An Bình, TP. Dĩ An',
    'P. Đông Hòa, TP. Dĩ An',
    'P. Bình An, TP. Dĩ An',
    'P. Bình Thắng, TP. Dĩ An',
    'P. Tân Bình, TP. Dĩ An',

    // TP. Bến Cát
    'P. Mỹ Phước, TP. Bến Cát',
    'P. Thới Hòa, TP. Bến Cát',
    'P. Tân Định, TP. Bến Cát',
    'P. Hòa Lợi, TP. Bến Cát',
    'P. Chánh Phú Hòa, TP. Bến Cát',

    // TP. Tân Uyên & Bàu Bàng
    'P. Uyên Hưng, TP. Tân Uyên',
    'P. Tân Phước Khánh, TP. Tân Uyên',
    'P. Thái Hòa, TP. Tân Uyên',
    'TT. Lai Uyên, Huyện Bàu Bàng',
  ],

  'Bà Rịa - Vũng Tàu': [
    // TP. Vũng Tàu
    'P. 1, TP. Vũng Tàu',
    'P. 2, TP. Vũng Tàu (Bãi Trước)',
    'P. 3, TP. Vũng Tàu',
    'P. 4, TP. Vũng Tàu',
    'P. 7, TP. Vũng Tàu',
    'P. 8, TP. Vũng Tàu',
    'P. 9, TP. Vũng Tàu',
    'P. Thắng Nhất, TP. Vũng Tàu',
    'P. Thắng Nhì, TP. Vũng Tàu',
    'P. Thắng Tam (Bãi Sau), TP. Vũng Tàu',
    'P. Nguyễn An Ninh, TP. Vũng Tàu',
    'P. Rạch Dừa, TP. Vũng Tàu',
    'Xã Long Sơn, TP. Vũng Tàu',

    // TX. Phú Mỹ (Thành phố cảng tương lai)
    'P. Phú Mỹ, TX. Phú Mỹ',
    'P. Mỹ Xuân, TX. Phú Mỹ',
    'P. Hắc Dịch, TX. Phú Mỹ',
    'P. Tân Phước, TX. Phú Mỹ',
    'P. Phước Hòa, TX. Phú Mỹ',
    'Xã Tóc Tiên, TX. Phú Mỹ',
    'Xã Châu Pha, TX. Phú Mỹ',

    // Huyện Xuyên Mộc (Hồ Tràm - Bình Châu)
    'Xã Phước Thuận (Hồ Tràm), Huyện Xuyên Mộc',
    'Xã Bình Châu (Suối Nước Nóng), Huyện Xuyên Mộc',
    'TT. Phước Bửu, Huyện Xuyên Mộc',
    'Xã Bông Trang, Huyện Xuyên Mộc',

    // TP. Bà Rịa & Huyện Long Điền
    'P. Phước Trung, TP. Bà Rịa',
    'P. Phước Hiệp, TP. Bà Rịa',
    'P. Long Toàn, TP. Bà Rịa',
    'TT. Long Hải, Huyện Long Điền',
    'Huyện Côn Đảo',
  ],

  'Hà Nội': [
    'P. Hàng Bạc, Quận Hoàn Kiếm',
    'P. Hàng Bồ, Quận Hoàn Kiếm',
    'P. Hàng Gai, Quận Hoàn Kiếm',
    'P. Tràng Tiền, Quận Hoàn Kiếm',
    'P. Lý Thái Tổ, Quận Hoàn Kiếm',
    'P. Điện Biên, Quận Ba Đình',
    'P. Đội Cấn, Quận Ba Đình',
    'P. Giảng Võ, Quận Ba Đình',
    'P. Kim Mã, Quận Ba Đình',
    'P. Dịch Vọng, Quận Cầu Giấy',
    'P. Dịch Vọng Hậu, Quận Cầu Giấy',
    'P. Trung Hòa, Quận Cầu Giấy',
    'P. Yên Hòa, Quận Cầu Giấy',
    'P. Quảng An, Quận Tây Hồ',
    'P. Nhật Tân, Quận Tây Hồ',
    'P. Xuân La, Quận Tây Hồ',
    'P. Ô Chợ Dừa, Quận Đống Đa',
    'P. Láng Hạ, Quận Đống Đa',
    'P. Mỹ Đình 1, Quận Nam Từ Liêm',
    'P. Mỹ Đình 2, Quận Nam Từ Liêm',
    'P. Mễ Trì, Quận Nam Từ Liêm',
  ],

  'Đà Nẵng': [
    'P. Hải Châu I, Quận Hải Châu',
    'P. Hải Châu II, Quận Hải Châu',
    'P. Thạch Thang, Quận Hải Châu',
    'P. Hòa Cường Bắc, Quận Hải Châu',
    'P. Hòa Cường Nam, Quận Hải Châu',
    'P. An Hải Bắc, Quận Sơn Trà',
    'P. An Hải Tây, Quận Sơn Trà',
    'P. Phước Mỹ, Quận Sơn Trà (Biển Mỹ Khê)',
    'P. Mỹ An, Quận Ngũ Hành Sơn',
    'P. Khuê Mỹ, Quận Ngũ Hành Sơn',
  ],

  'Khánh Hòa': [
    'P. Lộc Thọ, TP. Nha Trang (Đường Trần Phú)',
    'P. Phước Tiến, TP. Nha Trang',
    'P. Tân Lập, TP. Nha Trang',
    'P. Vĩnh Hải, TP. Nha Trang',
    'P. Vĩnh Hòa, TP. Nha Trang',
    'P. Phước Long, TP. Nha Trang',
    'Xã Cam Hải Đông, Huyện Cam Lâm (Bãi Dài)',
    'P. Cam Nghĩa, TP. Cam Ranh',
  ],

  'Lâm Đồng': [
    'P. 1, TP. Đà Lạt (Chợ Đà Lạt & Hồ Xuân Hương)',
    'P. 2, TP. Đà Lạt',
    'P. 3, TP. Đà Lạt',
    'P. 4, TP. Đà Lạt',
    'P. 8, TP. Đà Lạt (Thung Lũng Tình Yêu)',
    'P. 9, TP. Đà Lạt',
    'P. 10, TP. Đà Lạt',
    'P. 1, TP. Bảo Lộc',
    'P. B\'Lao, TP. Bảo Lộc',
    'TT. Liên Nghĩa, Huyện Đức Trọng',
  ],

  'Kiên Giang': [
    'P. Dương Đông, TP. Phú Quốc',
    'P. An Thới, TP. Phú Quốc (Nam Đảo)',
    'Xã Hàm Ninh, TP. Phú Quốc',
    'Xã Cửa Cạn, TP. Phú Quốc',
    'Xã Cửa Dương, TP. Phú Quốc',
    'Xã Gành Dầu, TP. Phú Quốc (Bắc Đảo)',
    'Xã Dương Tơ, TP. Phú Quốc (Bãi Trường)',
    'P. Vĩnh Thanh Vân, TP. Rạch Giá',
  ],

  'Cần Thơ': [
    'P. Tân An, Quận Ninh Kiều (Bến Ninh Kiều)',
    'P. An Cư, Quận Ninh Kiều',
    'P. An Hòa, Quận Ninh Kiều',
    'P. Cái Khế, Quận Ninh Kiều',
    'P. Xuân Khánh, Quận Ninh Kiều',
    'P. Hưng Phú, Quận Cái Răng',
    'P. Lê Bình, Quận Cái Răng',
    'P. Trà An, Quận Bình Thủy',
  ],

  'Bình Thuận': [
    'P. Hàm Tiến, TP. Phan Thiết (Mũi Né)',
    'P. Mũi Né, TP. Phan Thiết',
    'P. Phú Thủy, TP. Phan Thiết',
    'P. Thanh Hải, TP. Phan Thiết',
    'Xã Tiến Thành, TP. Phan Thiết (NovaWorld Phan Thiết)',
    'P. Phước Hội, TX. La Gi',
  ],
};
